# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63676f4e6dc8aa637d29c2d731e74d01b64e3af99cccc0264afac9c6b39b29b6ac75f3be4ee94555e7e410b88f602956175275c2c9f2f55ba3319523d89446b9

test:
  secret_key_base: 350c6041278b8f4e0c7d7553dbf80e7c3f5947bdb4eab0d6b9a4de19cb32740aad2e5693b5f7b07e06c38e0f5ea2da46074bba0ddd7c20fe5ba10ebd2d16cd0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
